### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by obriencj** [obriencj/koji-smoky-dingo#28]
```
$ koji list-tag-extras product-redacted-build
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/kojismokydingo/cli/__init__.py", line 349, in __call__
    return self.handle(options) or 0
  File "/usr/lib/python2.6/site-packages/kojismokydingo/cli/tags.py", line 711, in handle
    json=options.json)
  File "/usr/lib/python2.6/site-packages/kojismokydingo/cli/tags.py", line 677, in cli_list_tag_extras
    quiet=quiet)
  File "/usr/lib/python2.6/site-packages/kojismokydingo/cli/__init__.py", line 218, in tabulate
    print(fmt.format(*headings), file=out)
ValueError: zero length field name in format
2020-08-25 08:13:01,117 [ERROR] koji: ValueError: zero length field name in format
```

**Comment by obriencj** [comment]
In Python 2.6 (which RHEL 6 uses) format strings require explicit field names or numbers. The current implementation of tabulate uses a format string such as 

```{:<10}  {:<14}```  when it needs to be ```{0:<10}  {1:<14}```
