### ISSUE TITLE
koji timestamp format changed (breaks check-hosts)

### ISSUE THREAD

**Issue by obriencj** [obriencj/koji-smoky-dingo#36]
```
Traceback (most recent call last):
  File "/home/cobrien/.local/lib/python3.7/site-packages/kojismokydingo/cli/__init__.py", line 405, in __call__
    return self.handle(options) or 0
  File "/home/cobrien/.local/lib/python3.7/site-packages/kojismokydingo/cli/hosts.py", line 127, in handle
    options.quiet, options.shush)
  File "/home/cobrien/.local/lib/python3.7/site-packages/kojismokydingo/cli/hosts.py", line 43, in cli_check_hosts
    skiplist=ignore)
  File "/home/cobrien/.local/lib/python3.7/site-packages/kojismokydingo/hosts.py", line 94, in gather_hosts_checkins
    data = datetime.strptime(data, "%Y-%m-%d %H:%M:%S.%f %Z")
  File "/usr/lib64/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib64/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2020-09-21 11:28:33.055212+00:00 UTC' does not match format '%Y-%m-%d %H:%M:%S.%f %Z'
2020-09-21 07:29:13,819 [ERROR] koji: ValueError: time data '2020-09-21 11:28:33.055212+00:00 UTC' does not match format '%Y-%m-%d %H:%M:%S.%f %Z'
```

**Comment by obriencj** [comment]
Will need to implement some regex-to-strptime mapping function for more safely parsing time data.

**Comment by obriencj** [comment]
Triggered by https://pagure.io/koji/issue/2160
